spring.application.name=nucleo_1

spring.datasource.url=jdbc:postgresql://100.71.1.34:5432/nucleo1_db
spring.datasource.username=postgres
spring.datasource.password=wx7I2dDf2xtVTep1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update